---
- name: cloning the repo
  git:
    repo: https://github.com/UnpredictablePrashant/TravelMemory.git
    dest: /home/ubuntu/TravelMemory
    # update: yes
    # version: 'branch_or_commit'
  ignore_errors: yes
- name: updating url.js inside frontend
  shell: |
    echo 'export const baseUrl = "http://10.0.3.37:3001"' > /home/ubuntu/TravelMemory/frontend/src/url.js
- name: updating nginx
  shell: |
    echo "server {
            listen 80;
            listen [::]:80;
            server_name _;

            location / {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
            }
    }" > /etc/nginx/sites-available/default
- name: restart nginx
  shell: |
    sudo nginx -t
    sudo systemctl reload nginx  
- name: node install
  shell: |
    curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh
    sudo bash /tmp/nodesource_setup.sh
    sudo apt install nodejs -y
    node -v        
# - name: run frontend
#   shell: |
#     cd /home/ubuntu/TravelMemory/frontend
#     sudo npm install
#     sudo npm start &

#   - name: install pm2 globally
#   npm:
#     name: pm2
#     global: yes

# - name: run frontend with pm2
#   shell: |
#     cd /home/ubuntu/TravelMemory/frontend
#     pm2 start npm --name "frontend" -- start
#     pm2 save
- name: run frontend with nohup
  shell: |
    cd /home/ubuntu/TravelMemory/frontend
    sudo nohup npm start > /dev/null 2>&1 &