---
- name: Install and configure MongoDB on EC2 instance
  hosts: database
  become: yes
  tasks:
    - name: Update package list (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add MongoDB repository (Debian/Ubuntu)
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/5.0 multiverse"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install MongoDB (Debian/Ubuntu)
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add MongoDB repository (Amazon Linux)
      shell: |
        echo "[mongodb-org-5.0]
        name=MongoDB Repository
        baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/5.0/x86_64/
        gpgcheck=1
        enabled=1
        gpgkey=https://www.mongodb.org/static/pgp/server-5.0.asc" | sudo tee /etc/yum.repos.d/mongodb-org-5.0.repo
      when: ansible_os_family == "RedHat"

    - name: Install MongoDB (Amazon Linux)
      yum:
        name: mongodb-org
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Configure MongoDB to allow remote connections (Debian/Ubuntu)
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  bindIp:'
        line: '  bindIp: 0.0.0.0'
      notify: Restart MongoDB
      when: ansible_os_family == "Debian"

    - name: Configure MongoDB to allow remote connections (Amazon Linux)
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  bindIp:'
        line: '  bindIp: 0.0.0.0'
      notify: Restart MongoDB
      when: ansible_os_family == "RedHat"

    - name: Create MongoDB user
      mongodb_user:
        login_user: admin
        login_password: admin_password  # Replace with your password
        database: admin
        username: yourUsername
        password: yourPassword
        roles:
          - role: userAdminAnyDatabase
            db: admin

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted
