- name: Install MongoDB on Ubuntu 22.04
  hosts: database
  become: true

  vars_files:
    - ./roles/database/vars/vars.yml

  tasks:
    - name: Wait for dpkg lock to be released
      shell: |
        while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for dpkg lock...";
          sleep 5;
        done

    - name: Check Ubuntu version
      command: lsb_release -rs
      register: ubuntu_version

    # - name: Download MongoDB GPG key
    #   get_url:
    #     url: 'https://www.mongodb.org/static/pgp/server-6.0.asc'
    #     dest: '/tmp/mongodb-server-6.0.asc'
    #     validate_certs: false

    # - name: Add MongoDB GPG key using command
    #   command: apt-key adv --fetch-keys https://www.mongodb.org/static/pgp/server-6.0.asc

    # - name: Add MongoDB GPG key
    #   apt_key:
    #     file: '/tmp/mongodb-server-6.0.asc'
    #     state: present

    # - name: Add MongoDB APT repository
    #   apt_repository:
    #     repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse'
    #     state: present
    #     key: 'https://www.mongodb.org/static/pgp/server-6.0.asc'


    - name: Update apt cache
      apt:
        update_cache: yes  

    - name: Installing dependancies
      package:
         name: "{{item}}"
         state: present
         update_cache: yes
      loop:
        - curl
        - gnupg
        - python3-pip
      become: yes

    - name: Install pymongo
      apt:
        name: python3-pymongo
        state: present
        update_cache: yes

    - name: Install Python pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    # - name: Ensure pymongo 4+ is installed
    #   pip:
    #     name: pymongo
    #     version: ">=4.0"
    #     state: present
    # #     executable: /usr/bin/pip3
    #     extra_args: "--break-system-packages"

    - name: Install libssl1.1 for MongoDB
      shell: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
        sudo apt-get install -f -y  # Fix any dependency issues

    - name: Download and install MongoDB
      shell: |
        sudo apt install software-properties-common gnupg apt-transport-https ca-certificates -y
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        sudo apt update
        sudo apt install mongodb-org -y

    - name: Restart mongod
      shell: |
        sudo systemctl start mongod
        sudo systemctl enable mongod
        sudo systemctl restart mongod 
