- hosts: all
  become: yes
  tasks:

  - name: Update and install Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Install Flask and Python pip
    apt:
      name:
      - python3-pip
      - python3-flask
      state: present
      update_cache: yes

# - hosts: backend
#   become: yes
#   tasks:

#   - name: Update and install Nginx
#     apt:
#       name: nginx
#       state: present
#       update_cache: yes

#   - name: Install Flask and Python pip
#     apt:
#       name:
#       - python3-pip
#       - python3-flask
#       state: present
#       update_cache: yes

