- hosts: database
  become: yes
  roles:
  - database
  vars_files:
  - ./roles/database/vars/vars.yml

- hosts: backend
  become: yes
  roles:
  - backend
  vars_files:
  - ./roles/backend/vars/vars.yml



- hosts: frontend
  become: yes
  roles:
  - frontend
  vars_files:
  - ./roles/frontend/vars/vars.yml