- hosts: frontend
  become: yes
  tasks:

  - name: Update and install Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Install Flask and Python pip
    apt:
      name:
      - python3-pip
      - python3-flask
      state: present
      update_cache: yes

  - name: cloning the repo
    git:
      repo: https://github.com/UnpredictablePrashant/TravelMemory.git
      dest: /home/ubuntu/TravelMemory
      # update: yes
      # version: 'branch_or_commit'    

  - name: node install
    shell: |
      curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh
      sudo bash /tmp/nodesource_setup.sh
      sudo apt install nodejs -y
      node -v    



- hosts: backend 
  become: yes
  tasks:

  - name: Update and install Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Install Flask and Python pip
    apt:
      name:
      - python3-pip
      - python3-flask
      state: present
      update_cache: yes

  - name: cloning the repo
    git:
      repo: https://github.com/UnpredictablePrashant/TravelMemory.git
      dest: /home/ubuntu/TravelMemory
      # update: yes
      # version: 'branch_or_commit'    

  - name: node install
    shell: |
      curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh
      sudo bash /tmp/nodesource_setup.sh
      sudo apt install nodejs -y
      node -v    